### ISSUE TITLE
[Feature Request] Add support for "Silver Standard"

### ISSUE THREAD

**Issue by Handyfon** [DFreds/dfreds-pocket-change#1]
Please add an option to convert the generated money for the silver standard rules:
10 copper to 1 silver, 
100 silver to 1 gold, 
100 gold to 1 platinum.

**Comment by DFreds** [comment]
Sure, should be easy. I can probably do that either tonight or tomorrow. Good suggestion!

**Comment by DFreds** [comment]
@Handyfon quick question for ya, since you're the feature requester. How would you like 'leftover' currencies to be handled? Say I generated 12 cp. Do you want 10 sp and 2 cp or just the 10 sp?

**Comment by Handyfon** [comment]
I'd like to generally keep the same amount of coins, so 1 sp and 2 cp ^^

**Comment by DFreds** [comment]
Added support for this in Release 1.2. Enjoy!
