### ISSUE TITLE
Add support for generating items with rollable tables

### ISSUE THREAD

**Issue by DFreds** [DFreds/dfreds-pocket-change#11]
**Ask** (via @dangerdaren): Finally, (and this probably could be solved with just a macro, or a commented out section in an existing macro that could be replaced), I'd like to be able to trigger a roll table to drop loot into the NPC's inventory. For instance, currently I have it set where CUB triggers your macro to make the NPC lootable. It simultaneously triggers a macro that I have set up that rolls a rolltable of rolltables (using the Loot Table by Better Roll Tables module). Currently all the resulting items from my rolltable show up in the chat window. I'd love it if I could make those items drop into the loot sheet automatically. I've attached an image of my rolltable set up for clarity. Actually, what I'd really love is for a window to pop up where I could approve/disapprove which items from the table will be dropped into the sheet from my rolltable result, but maybe I'm getting out of hand here!

**Use case**: Auto generation of items/common loot

**Potential solution**: Unsure. Either hook into LootSheet somehow to use its built-in method, or add new macro that adds items based on a specified roll table.

**Example rollable table**:
![](https://user-images.githubusercontent.com/70997865/108144643-f1367400-707e-11eb-9532-676aae4cd5a9.png)

**Comment by p4535992** [comment]
Hi, my suggestion is to use the mechanism of the module "[Innocenti Looting] (https://github.com/rinnocenti/innocenti-looting#loot-items-rolltables)" which seems to work fine, I don't think there are any problems to reuse the code,  just insert a link to the innocenti project in the credits.

It's literally the only thing that forces me to use both modules, but I think your integration with LootSheet is a better idea.

**Comment by p4535992** [comment]
If you use the module [Loot Populator NPC 5E](https://github.com/DanielBoettner/fvtt-loot-populator-npc-5e), you can manage this use case, and perhaps it is a better solution to be able to manage these two things separately in two separate modules.
You can probably close this issue.

**Comment by DFreds** [comment]
Thanks for bringing that module to my attention. You're right, I probably would have separated that functionality into a new module anyway.
