### ISSUE TITLE
Exchange items with items from compendium.

### ISSUE THREAD

**Issue by RustyXXL** [DFreds/dfreds-pocket-change#15]
**Is your feature request related to a problem? Please describe.**
When converting a npc to loot it's quite common, that the npc has it's own type of an item, not the one players loot.
i.e. Goblins have their own version of a scimitar, that references goblins in the description, might not have value or weight etc.

**Describe the solution you'd like**
It would be nice to have the option to exchange items with normal versions from a Compendium.
ie. when converting said goblin to loot, look in my configurable items compendium and replace the item with one from the compendium with the same name if it exists. If the item doesn't exist, just convert the same way as it does now.

**Comment by DFreds** [comment]
Hm, interesting. Currently, all the loot conversion stuff is pretty self-contained away from the application. I could probably update the macro to do this, but I don't think this is a very common use case. Is there any reason why you wouldn't just create the goblin using your custom items?

**Comment by RustyXXL** [comment]
All my Monsters and Items are imported via ddbimporter.
Also while the NPCs still have them it makes sense that they still are the monster version.
I don't know how common this is, I just thought it would be usefull to have. I probably could also update the macro myself...dunno, just thought it might be a good idea.

**Comment by DFreds** [comment]
Yeah, this seems out of scope for this module and is too small of a use case. You could easily write your own macro that executes right before/after my macro, though.
