### ISSUE TITLE
send generated currency amounts to chat

### ISSUE THREAD

**Issue by sharkbruhaha** [DFreds/dfreds-pocket-change#16]
Would be good to see how much currency is generated when either macro is run, so that GM can read off to the player(s) when they are looking, instead of having to open sheets to see. (also to make sure that generate currency happened since there is no feedback atm since no field on the default/tidy npc sheets) 

Process:
```
1) select token(s)
2) run generate currency macro
   2b) or when gen loot sheet macro run
3) output to chat the amount of currency on each
```

**Comment by DFreds** [comment]
Correct me if I'm wrong, but I believe the intent of your ask was to know how much money was on an NPC. With the release of 3.0.0, you can now view how much money they have directly from their sheet. So I'm not sure if this request is still valid to you... Let me know.

**Comment by sharkbruhaha** [comment]
Yes, but the outputting the result as blind gm so that I know without having to click into the sheets is convenience option, and is a nice indicator that the macro did something without having to open multiple actors (with the gen currency macro specifically, but figure do both since they're prob using the same function).

**Comment by DFreds** [comment]
Okay, just checking. I can still add that feature

**Comment by DFreds** [comment]
Added this in v3.1.0
