### ISSUE TITLE
Additional Sheets Request

### ISSUE THREAD

**Issue by ravingdragoon** [DFreds/dfreds-pocket-change#19]
I am hoping it might be possible to add the Obsidian compatibility and Merchant Sheet NPC compatibility.

**Comment by DFreds** [comment]
Sorry, lost track of this somehow. 

Adding these sheets are low on my priority list at the moment. I haven't used either of them so it'll take some time.

I'm also confused why you would want to convert a merchant to a loot sheet or do the other stuff on it, but maybe your players are murder hobos. If they aren't, that might be better off being a request on the merchant loot sheet NPC repository to display the currency. Same for obsidian, honestly. Tidy recently started automatically showing the NPC currency row, and that would make it much easier.

**Comment by p4535992** [comment]
This ticket can be closed other modules do this eventually
