### ISSUE TITLE
Customize "isHumanoid" behaviour

### ISSUE THREAD

**Issue by benbarbour** [DFreds/dfreds-pocket-change#2]
Great module, thanks! Would it be possible to have a setting to customize what counts as a humanoid? Or to change the setting to "Add Loot to These Types" and have the value be a list of strings? Possibly defaulting to the list of default 5e player races. A lot of my NPCs are currently set up with just their racial type listed. Meaning "Gnome" instead of "Humanoid (gnome)" or whatever.

This would also allow me to temporarily add "undead" to the list while placing a bunch of skeletons or vampires or whatever else might have some currency, but then remove it when placing the ghosts. Actually, that just made me realize that for now I can just toggle "Humanoids Only" off and on while placing tokens. Still, I think the type-customization might be nice going forward.

**Comment by benbarbour** [comment]
Actually, could the decision just be made on the fly when I click the macros? Like, one macro for "Make Lootable", a separate one for "Add Currency", and maybe one convenience wrapper of "Add Currency and Make Lootable". Then I just decide in the moment during the game. It'd still need to be a mod for a few of the global settings I think (% chance is nice).

**Comment by DFreds** [comment]
I was already considering adding a macro for making a token lootable on demand. So expect that in the future. 

As far as what counts as 'humanoid' or not, I was hoping someone would provide some more use case on that. I can probably switch that to a comma separated list or something. Let me see what I can come up with.

**Comment by DFreds** [comment]
As a temporary workaround, you could add something like Gnome (humanoid) and then this module will work. It just looks for that string. But I'll try to have something out soon.

**Comment by DFreds** [comment]
I went ahead and implemented the isHumanoid logic in v1.3.0. There is a new configuration field that will accept a list of creature types. Give it a shot!

Also, I'll make a new issue to add some macros to do it on the fly.
