### ISSUE TITLE
Incapability with Token HUD Wildcard

### ISSUE THREAD

**Issue by alcobeard** [DFreds/dfreds-pocket-change#20]
Enabling functionality of Token HUD Wildcard for certain token disabling auto-generate currency feature. At the same time feature works fine with other "standard" tokens. 

P.S. we can generate loot using macro or button in NPC sheet

**Comment by DFreds** [comment]
If you create a bug, please do not delete the template it provides. You need to fill it as requested. As it stand, I have no idea what is going on here, but it doesn't seem like a bug. Maybe it's a feature request? No clue. Remake this if you need to
