### ISSUE TITLE
Converting NPCs with vision to lootable 

### ISSUE THREAD

**Issue by Resfelm** [DFreds/dfreds-pocket-change#23]
### Description
When converting an NPC to lootable, if the NPC has vision, players can see what the NPC sees when the **deselect** their character.

**Repo steps:**
This is happening on 
FVTT v. 0.8.8
DnD5e v. 1.4.2

1. Set the scene vision and lighting settings as shown in the screenshot 
![image](https://user-images.githubusercontent.com/25343704/132057651-53a40dee-1218-4294-9a35-b8be107b22c9.png)
2. Add an NPC and a player token on the scene. Make sure there is no line of sight between the player and the NPC by placing them in different rooms or placing some walls between them.
3. Add vision to the NPC if it does not already have it. The player token should also have vision enabled.
4. Make sure the Player and NPC can acctualy see in the current set up, i.e. they have dark vision or lights are placed close to them.
5. Select the NPC and convert it to lootable.
6. Logged in as the player, load into the scene and click (or click and drag) on empty space to deselect your character token. 
7. You should now be able to see whatever the lootable NPC can see.

**Expected behavior**
The player should not be able to see what the lootable NPC can see, under any circumstances. 

**Screenshots**
1. Player with their charater token selected, they can see what they should.
![foundry_bug_token_selected](https://user-images.githubusercontent.com/25343704/132058020-9520e4d3-b95e-44e3-88d0-0bc5f04364dd.png)

2. Player with their character token deselected, they can see what NPCs converted to lootable can see, based on current light settings.
![foundry_bug_token_not_selected](https://user-images.githubusercontent.com/25343704/132058128-6655e2dc-83cf-48ad-8b22-d3f0287afa92.png)

**Suggestion**
Automatically disable token vision when it is converted to lootable.

**Comment by DFreds** [comment]
Good find! I basically never have vision set for NPCs, so I didn't notice. I'll fix it

**Comment by DFreds** [comment]
Fixed in v3.1.3
