### ISSUE TITLE
Move Currency amounts out of JS into Compendium or Rolltable for customization

### ISSUE THREAD

**Issue by ngPescado** [DFreds/dfreds-pocket-change#24]
I love the simplicity of this module. However, I wonder if there could be an enhancement if the currency tables for various CRs was moved out of the main script into calls to prebuilt compendiums and/or roll tables. This would possibly empower the DM to build their own levels of SP/GP/etc for CR 0-4, CR 5-10, etc.. 

Granted it does introduce some complexity so may be outside the goals of the module. Loot Populator NPC 5e does this to some degree but I much prefer DFred modules :) Cleaner.

**Comment by DFreds** [comment]
I don't think this is something I want to do. I also like the simplicity of the module, and I'd rather avoid having to do weird things like abusing roll tables to let you configure the values. If Foundry ever adds an easier way to configure things like tables, I'll consider it. But until then, you can use the currency multiplier setting to get a mild amount of control over how much it generates.
