### ISSUE TITLE
"Convert Lootables" button has hidden dependency on "Monk's Tokenbar" module

### ISSUE THREAD

**Issue by asciodev** [DFreds/dfreds-pocket-change#25]
**Describe the bug**
The "Convert Lootables" button on the right-hand sidebar is not visible when "Monk's Tokenbar" module is not active.

**To Reproduce**
1. Create a new test world using D&D5e as a system.
2. Launch world as gamemaster.
3. Enable only the following modules: "DFred's Pocket Change",  "Loot Sheet NPC 5e", "Monk's Tokenbar"
4. Observe that the "Convert Lootables" button is visible in the right-hand sidebar.
5. Disable "Monk's Tokenbar" module.
6. Observe that the "Convert Lootables" button is no longer visible in the right-hand sidebar.

**Expected behavior**
The "Convert Lootables" button should appear when only "DFred's Pocket Change" and "Loot Sheet NPC 5e" modules are active.

**Screenshots**
1. "Convert Lootables" button visible when "Monk's Tokenbar" module is active
![image](https://user-images.githubusercontent.com/81930475/132259856-2df5b601-ef4a-451d-a272-b16bc99376ca.png)
2. "Convert Lootables" button no longer visible when "Monk's Tokenbar" module is inactive
![image](https://user-images.githubusercontent.com/81930475/132259964-674cde64-ba44-41c1-9c72-2813980e5c01.png)

**Additional Context**
Foundry Version: 0.8.9
D&D 5e System Version: 1.4.2

**Comment by DFreds** [comment]
That button isn't added by this module. I'm guessing it's added by Monk's Tokenbar.
