### ISSUE TITLE
Toggle Chest Icon on lootable

### ISSUE THREAD

**Issue by DuckDungeon** [DFreds/dfreds-pocket-change#26]
The chest icon is a nice touch, but a bit too obvious for my players. Right now on death my npcs become bloody corpses thanks to CUB, but the chest icon hides all of it.

The quality of life I get from pocket change and the call to change to lootable automatically is really great, the chest icon is a minor annoyance in my games.

**Comment by DFreds** [comment]
Fair enough! I can make that an optional feature.

**Comment by DuckDungeon** [comment]
Looking forward to it :)

**Comment by DFreds** [comment]
Added a new setting in v3.1.4

https://raw.githubusercontent.com/DFreds/dfreds-pocket-change/main/docs/settings.png
