### ISSUE TITLE
Console and chat says loot generated, but not on character sheet

### ISSUE THREAD

**Issue by ghoulapool** [DFreds/dfreds-pocket-change#27]
When I drag/drop an actor who could have currency on them, the chat says (for example) 

![image](https://user-images.githubusercontent.com/36716334/133938919-bb0da58e-02a1-4a53-af60-7bdffae4f45f.png)

And console says it too . . .

![image](https://user-images.githubusercontent.com/36716334/133938943-6aa8eadb-876f-4af1-8cf9-8bddf0d41e18.png)

But as you can see, there's no coins on this guy.

![image](https://user-images.githubusercontent.com/36716334/133938961-12402d63-b841-49c8-8ef4-e3c8e738c646.png)

Interestingly, if I use the button in that sheet to generate coins - it works:

![image](https://user-images.githubusercontent.com/36716334/133939000-37544b59-5b91-4d79-94c4-bc6117cf414e.png)

Perhaps I'm confused on the use, but it SEEMS to think it's generating coins when it isn't.  Am I doing something wrong or is this a bug?  Perhaps something else stomping on it?

**Comment by ghoulapool** [comment]
Maybe worth noting that when use the "generate currency" button, it does the same print out to Chat.  Here I'm showing another generate where you can see both the sheet and the Chat output.

![image](https://user-images.githubusercontent.com/36716334/133939045-41ffff19-0cc4-4d6d-aada-d2294a1e1b30.png)

**Comment by Jedstonk** [comment]
I'm running into the same issue for some of my tokens. I've been able to narrow down the issue (on my side anyway) to when the wildcard images is selected.

![image](https://user-images.githubusercontent.com/89883224/133966097-651d56e7-2a53-4f17-8b05-b50722b2653a.png)

Whenever I disable this setting from the token the currency is generated dynamically.

**Comment by DFreds** [comment]
Huh, okay. Let me try to reproduce that and see what is happening

**Comment by DFreds** [comment]
Did either @ghoulapool or @Jedstonk get anything in the console log when it fails?

**Comment by DFreds** [comment]
I was able to solve the issue with wildcard images. That is fixed in v3.1.5.

I'm assuming that is what happened to you @ghoulapool. Let me know if the issue persists after updating
