### ISSUE TITLE
Equipment is never damaged

### ISSUE THREAD

**Issue by w1face** [DFreds/dfreds-pocket-change#28]
No matter what I set the sliders to... when I convert the creature to a lootable, the equipment is never damaged, and is always full price.

**Comment by DFreds** [comment]
Only items with a rarity of 'Common' can be damaged. Also, it could relate to this issue, which would mean something migrated incorrectly. Try doing it on an actor imported newly from the dnd5e compendium.

https://github.com/DFreds/dfreds-pocket-change/issues/21

**Comment by w1face** [comment]
Yup, it's where I import the monsters from.  Worked fine with the SRD
import.  Cheers

**Comment by DFreds** [comment]
That's usually a migration error, or that old actors didn't have rarity on items. I don't know which though. But glad it's resolved!
