### ISSUE TITLE
damaged items dont work

### ISSUE THREAD

**Issue by CaosFR** [DFreds/dfreds-pocket-change#31]
**Describe the bug**
Hi,

I have a problem with the option "Damaged Items". I would like to my PC never loot items, just gold.
But damaged items are always intact and never remove.
Hope it's not become I'm french again :)

Thanks

**To Reproduce**
1. Change 'Chance of Damaged Items' to 1 (tested on 0 to)
2. Click on "Convert Lootables" on dead NPC with some stuff (like a Bandit)
3. Look inside LootSheet5eNPC. I can always loot all items

**Expected behavior**
Loot nothing in dead body

**Screenshots**
<img width="822" alt="Capture" src="https://user-images.githubusercontent.com/37581932/141832193-2a679400-8feb-44b6-a772-fd154480b723.PNG">

**Additional context**
No error on F12. My compendium and DnD system are in french.

**Comment by DFreds** [comment]
This can sometimes happen due to migration issues. Can you re-import an actor from the monsters compendium and try again on that one? I'll look into it further if it remains an issue.

**Comment by CaosFR** [comment]
Thanks for your quick answer.
I have already try to remove "Bandit" from "Actor tab" and re-import them but the problem persist.
For information, this tips had solve gold generation before I post my problem.

**Comment by CaosFR** [comment]
Edit : If I use your macro "Convert Selected Tokens to Loot" it's work, but, If I click on "Convert Lootables" I have the bug.
Hope it's will help.

**Comment by DFreds** [comment]
> Edit : If I use your macro "Convert Selected Tokens to Loot" it's work, but, If I click on "Convert Lootables" I have the bug. Hope it's will help.

That is strange, and definitely helpful. I'll look into it

**Comment by CaosFR** [comment]
I have find something, "Convert Lootables" button come from Monk-tokenbar module right ?
I dont see any button from your mob or loot-sheet.
Maybe it's a incompatiblity ?

https://github.com/ironmonk88/monks-tokenbar#lootables
Lootables
New to 1.0.15 added support for converting npc's to lootable if you have the Lootsheet module installed. TokenBar will remove all feats of the character that should not be lootable and will save them so that the character can be reverted back from lootable.
