### ISSUE TITLE
Not Lootable Aftet Executing Macro

### ISSUE THREAD

**Issue by Instg8r2000** [DFreds/dfreds-pocket-change#33]
After executing the 'convert to lootable' macro, the npc's attribute sheet still shows up instead of the lootable sheet, and therefore cannot be looted. When I change it to the lootsheet manually, noting appears. The lootable icon will still show up on the token however.

**Comment by DFreds** [comment]
Is this on v9?

**Comment by Instg8r2000** [comment]
No, V8.9. Just started happening in the last few week.

**Comment by DFreds** [comment]
Fixed in v3.2.1. Caused by loot sheet making some breaking changes in their latest update

**Comment by Instg8r2000** [comment]
Thank you!
