### ISSUE TITLE
Compatibility with Monk's Enhanced Journal loot sheets

### ISSUE THREAD

**Issue by weepingminotaur** [DFreds/dfreds-pocket-change#36]
Given that LootsheetNPC5e is broken and hasn't been updated in months, and given the fact that an increasing number of users are using Monk's Enhanced Journal to manage loot, compatibility with MEJ loot sheets would be excellent. Users could choose which lootable system they want to use (MEJ or Lootsheet).

**Comment by weepingminotaur** [comment]
Yeah, it's one of MEJ's lesser-known features, but it's pretty solid. Thanks for looking into it!

**Comment by DFreds** [comment]
I think supporting various lootable methods is getting out of scope for this module. I don't like relying on other modules to update and work appropriately. This module creates the currency on the actor automatically... other loot modules can use that as they wish.
