### ISSUE TITLE
[Feature Request] Integration with Item Pile macro for generate currency on the npc

### ISSUE THREAD

**Issue by p4535992** [DFreds/dfreds-pocket-change#37]
**Is your feature request related to a problem? Please describe.**

Integration of this macro [NPC-to-Coin-Pile](https://github.com/Shuggaloaf/NPC-to-Coin-Pile) in the module,  but in general a integration with Item Piles is the right direction to follow.

Optional feature:  add a Token HUD button for convert the token to lootable and reverse, item pile let you do that.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DFreds** [comment]
Hey, picking up on this module again... This is coming as soon as Item Piles is updated for v10.

**Comment by p4535992** [comment]
Connected to https://github.com/DFreds/dfreds-pocket-change/issues/42
