### ISSUE TITLE
One entity for all killed NPC after combat

### ISSUE THREAD

**Issue by CaosFR** [DFreds/dfreds-pocket-change#39]
**Is your feature request related to a problem? Please describe.**
Hi, simple request for this beautifull module. When combats are finish my players rush to open all killed NPC. It's pretty cool, but it's a little chaos when they are 30 deads bodys.

**Describe the solution you'd like**
A "chest" with all items and currency will pop on the battlemap at the end of the fight.

**Describe alternatives you've considered**
All items/currency will be transfert from dead NPC at the end of the combat. On the next battle this chest will be clear from previous items.

**Additional context**
Monk's TokenBar make something like that but without damaged items or a good monnaie calcul. So a easier way will be to use you currency calcul and create a new macro for destroy items. We can use Monk TokenBar just for transfer all items to a single entity.

**Comment by DFreds** [comment]
This seems a little out of scope for this module. The main goal of this modules is to generate currency and put it on the actor sheet.

**Comment by CaosFR** [comment]
May can we have a macro for just destroy item inside a sheet ? With a other module we can transfert item in a single entity.
