### ISSUE TITLE
v10 version of Pocket Change not showing up on The Forge

### ISSUE THREAD

**Issue by weepingminotaur** [DFreds/dfreds-pocket-change#40]
Last version available on the Forge is 3.2.1.

**Comment by DFreds** [comment]
Is this the only one that is not showing up in the forge out of my modules for v10?

**Comment by weepingminotaur** [comment]
Yep, the only one. Your other mods show up fine in the Forge.

**Comment by DFreds** [comment]
This was caused by an old release of 4.0.0 back in December 2021 that I deleted. The Forge still had it picked up and hid it for me back then. This should be fixed now with 4.0.1
