### ISSUE TITLE
v10 support with Loot Sheet?

### ISSUE THREAD

**Issue by tristanvann** [DFreds/dfreds-pocket-change#41]
In the readme, it says this module requires Loot Sheet NPC 5e. That module is not updated for v10. This module says it is updated for v10. How does that work exactly? Is Loot Sheet actually usable with v10, despite saying only v9? I don't want to install it and risk breaking things if its not actually compatible.

**Comment by DFreds** [comment]
Ah, loot sheet is not required anymore to get some functionality out of this. I'll remove that from the readme. But this does include some macros that integrate with loot sheet.... which simply won't work until it is updated to v10.

**Comment by Shayulghul** [comment]
It looks like the loot sheet module was updated in January to work with v10. Everything seems to be working OK for me except for switching the actor's sheet.

**Comment by DFreds** [comment]
Should be fixed due to #44
