### ISSUE TITLE
FoundryVTT-ItemPiles with Dfreds-pocket-cgabge

### ISSUE THREAD

**Issue by CaosFR** [DFreds/dfreds-pocket-change#42]
**Is your feature request related to a problem? Please describe.**
Loot Sheet NPC 5e is'nt compatible with v10

**Describe the solution you'd like**
Find a alternative to Loot Sheet NPC 5e

**Describe alternatives you've considered**
Hi, do you think you can make this module compatible with [FoundryVTT-ItemPiles](https://github.com/fantasycalendar/FoundryVTT-ItemPiles) ainstead of Loot Sheet ?

**Additional context**
Thanks

**Comment by ChobitsCrazy** [comment]
Second this, Item piles is a great module would love to see this!

**Comment by DFreds** [comment]
I'm pushing back on this. Item piles should be the one to support any and all things that convert it to an item pile. Since this module simply adds coinage to an NPC, it should be no trouble for item piles.
