### ISSUE TITLE
Convert to Loot does not set the Sheet to a LootSheet

### ISSUE THREAD

**Issue by deadpyxel** [DFreds/dfreds-pocket-change#44]
**Describe the bug**
When converting a token to loot the token sheet stays the same/the global default.

**To Reproduce**
1. Drag an NPC actor into the canvas
2. Select the token created
3. Either use the macro or click in the "convert to Loot" button on NPC sheet
4. See that features, special itens and such are removed, the permission is set to observer and the overlay icon is set, but the token sheet does not change to a loot sheet

**Expected behavior**
When using the convert to loot option, the sheet type should change to a loot sheet automatically, as per the documentation.

**Screenshots**
Here is the output on console about the loot generation:
<img width="552" alt="image" src="https://user-images.githubusercontent.com/8644691/231489756-90043690-e96c-4c3b-932b-49786efe03d7.png">

**Additional context**
I am using FoundryVTT v10, build 291, with Dnd5e system version 2.1.5

I also have the latest version for both Tidy 5e sheet and lootsheet NPC
<img width="679" alt="image" src="https://user-images.githubusercontent.com/8644691/231491538-453627a0-401a-4962-bd4d-6948bd6e961d.png">

Result after conversion:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/8644691/231492000-f733cf38-2aa5-40ca-91b0-6b94f5424e88.png">

I noticed that with the migration for V10, the name fo lootsheet NPC module changed to lootsheet-simple, maybe this is something that is interfering?

**Comment by deadpyxel** [comment]
I just found out that the identifier for npc loot sheet has changed to `dnd5e.LootSheet5eNPC`, while in the code is using `dnd5e.LootSheetNPC5e` as value. I think I can make a PR fixing it, but I am not very well versed on JS.

**Comment by Shayulghul** [comment]
I'm having the same issue.

**Comment by DFreds** [comment]
Awesome, thanks for reporting and fixing!
