### ISSUE TITLE
Will it be updated to v11?

### ISSUE THREAD

**Issue by GabrielOsvair** [DFreds/dfreds-pocket-change#47]
Hello! Congratulations on the module, I really like it and would like to know if it will be updated to v11.

**Comment by DFreds** [comment]
Eventually. It's a little more challenging than all the others due to some API changes. Right now, it's not at the top of my priority list though

**Comment by GabrielOsvair** [comment]
Alright, thanks for the reply. I'll look to see if any macros scroll a table and add the items, for now.

**Comment by GabrielOsvair** [comment]
A suggestion: Compatibility with Item Piles

**Comment by DFreds** [comment]
Closing as this will just happen eventually and doesn't need tracked. Also, item piles compatibility is in the works
