### ISSUE TITLE
Mark Loot Sheet NPC 5E as dependency so that the Module Management screen will track it

### ISSUE THREAD

**Issue by TheRealIceCracker** [DFreds/dfreds-pocket-change#48]
**Is your feature request related to a problem? Please describe.**
Loot Sheet NPC 5E isn't marked as a dependency, so the Module Management screen won't notify you if you don't have that installed as well. This renders this module non-functional with no clear in-app indication why.

**Describe the solution you'd like**
Loot Sheet NPC 5E marked as a dependency such that the Module Management screen will notify you if you don't have that installed or enabled.

**Describe alternatives you've considered**
At the end of the day I figured it out just by reading the module description again, but most other modules have this functionality and I assume (please don't crucify me if it's not) that it's pretty low lift.

**Additional context**
N/A

**Comment by DFreds** [comment]
The whole thing needs a rewrite, and might not rely on any loot sheet when its done. Closing this for now
