### ISSUE TITLE
v11 Support

### ISSUE THREAD

**Issue by mfozz** [DFreds/dfreds-pocket-change#49]
**Is your feature request related to a problem? Please describe.**
Pocket Change works great in v10, but it doesn't seem to be supported in v11.

**Describe the solution you'd like**
I was just wondering whether it'll be support v11+.

**Describe alternatives you've considered**
I was going to look at Innocenti's Loot, but I really like how clean the DFred documentation is and how easy it is to use the modules.

**Additional context**
Nothing, just thanks for all the hard work you put into these modules

**Comment by mcmackj** [comment]
Second to the question

**Comment by mfozz** [comment]
UPDATE: I downloaded the module and updated the json file to be v11 so I could activate the module in the electron app. The module is working well for the most part. The conversion scripts are working, and it's working well with Loot Sheet 5e. 

One thing I'm still testing is the loot conversion (money is generating, but the monsters' weapons aren't showing up as loot). I think it just need a bit of testing and someone to update the manifest so we can install it in v11.

**Comment by DFreds** [comment]
Fixed in v5.0.0
