### ISSUE TITLE
Feedback/Suggestions

### ISSUE THREAD

**Issue by dangerdaren** [DFreds/dfreds-pocket-change#7]
Fantastic module! I've got a few ideas that would make it insanely perfect (for my very specific use anyway):

I'm running the Combat Utility Belt module, and I've rigged it with Triggler so when an NPC hits zero hit points, it triggers the "Generate Currency and Convert to Loot for Selected Tokens" macro. This is awesome, since once the NPC's health drops to <=0, it pops up a window asking if I wanna convert said NPC. Beautiful!

Feedback:

1.) One concern is it might be best if instead of triggering on the selected token, I wonder if there is a way to make it apply to "whichever token triggered the event". Just in case I'm selecting someone else when an NPC dies. Maybe as simple as a new macro/line of code in existing macro to get triggered instead?

2.) Settings wise, I would love a bit more granularity. For example. I never use platinum in my game, and would like the option to nix that from being handed out (similar to how I also don't use electrum, which I do appreciate being able to nix that one in the options!).

3.) I also would love the option to set a percentage of chance that armor/weapons are too damaged to be included in the loot. I can already imagine my players stockpiling weapons from the dead unnecessarily just because they can, lol.

4.) Finally, (and this probably could be solved with just a macro, or a commented out section in an existing macro that could be replaced), I'd like to be able to trigger a roll table to drop loot into the NPC's inventory. For instance, currently I have it set where CUB triggers your macro to make the NPC lootable. It simultaneously triggers a macro that I have set up that rolls a rolltable of rolltables (using the Loot Table by Better Roll Tables module). Currently all the resulting items from my rolltable show up in the chat window. I'd love it if I could make those items drop into the loot sheet automatically. I've attached an image of my rolltable set up for clarity. Actually, what I'd really love is for a window to pop up where I could approve/disapprove which items from the table will be dropped into the sheet from my rolltable result, but maybe I'm getting out of hand here!

![Screen Shot 2021-02-16 at 4 39 07 PM](https://user-images.githubusercontent.com/70997865/108144643-f1367400-707e-11eb-9532-676aae4cd5a9.png)

**Comment by DFreds** [comment]
These are all good ideas. Let me respond to each one individually.

1. This should be doable. I'll probably do a check to see if a token is passed in and if not, use the selected one. I just need to figure out the syntax for how the arguments are passed.
2. This is easy enough, but I would like some more clarity on the level of granularity. Let me know exactly what settings would be useful for you, and I can translate that. For instance, do you want some check boxes that allow you to decide which currencies are included or something like that? 
3. This one is very easy. I'll just add a couple checks to ensure we're not deleting any magic items.
4. I had considered doing it in the past, but Loot Sheet NPC 5e already has this functionality built into the sheet itself. Meaning, you could manually switch it over to a Loot Sheet, generate the items, and then switch back to a regular sheet. However, you're the second person who has asked for this, so I'll look into it more. Maybe I can hook into something Loot Sheet exposes and populate it that way. But yeah, we'll see for it. If I am able to figure it out, it won't be for a while.

**Comment by dangerdaren** [comment]
Excellent! As for the granularity of #2, checkboxes would work perfectly, 1 for each denomination of coin.

Too bad about #4, I tried the idea of swapping back and forth on Loot Sheet, but it was pretty clumsy, since I'd have to choose the roll table and adjust the formula each time. My current macro is smoother where it rolls automaticallyand I drag from the chat window into the sheet. I'll keep that up for now.

Glad they're helpful ideas. Thanks for creating such a great module. I love letting my player loot, but it's always been clumsy. This module kicked my butt into gear to make a good roll table, and now I can implement it far better than before. Looking forward to the update!

**Comment by DFreds** [comment]
Hey @dangerdaren, I'm glad you enjoy the module. It's great hearing that type of thing. 👍 

I went ahead and created four separate issues based on your requests (#8, #9, #10, and #11) as I will probably be including these in four separate releases. Feel free to add any other important details to the corresponding issue. I'm going to close this one as a result.
