### ISSUE TITLE
Add support for CUB triggers in macros

### ISSUE THREAD

**Issue by DFreds** [DFreds/dfreds-pocket-change#8]
**Ask** (via @dangerdaren): One concern is it might be best if instead of triggering on the selected token, I wonder if there is a way to make it apply to "whichever token triggered the event". Just in case I'm selecting someone else when an NPC dies. Maybe as simple as a new macro/line of code in existing macro to get triggered instead?

**Use case**: convert token to loot when token reaches 0 HP

**Potential solution**: Add support for passing a token in as an argument to all macros

**Comment by DFreds** [comment]
Regarding CUB specifically, this seems to be an open issue: https://github.com/death-save/combat-utility-belt/issues/453

Marking as blocked until CUB supports it.

**Comment by SR5060** [comment]
I agree, this would be very handy. is there a way that the macro can check for a token that meets the criteria (NPC & HP at 0) so that it's not dependent on triggler for actor identification?

**Comment by DFreds** [comment]
Do you mind posting the macro you're talking about? I can look into why it isn't working now, and it would help me understand what your use case was in detail.

**Comment by SR5060** [comment]
This includes code from your macro, using the other macro for triggering purposes:

`(async () => {
    let defeated = canvas.tokens.placeables.filter(t => {
        return t.data.disposition === -1 && t.data.actorData.data?.attributes?.hp?.value <= 0
    });

    for (let token of defeated) {
        if (token.actor.data.type != 'npc')
            continue;

        let invalid = await token.getFlag(`world`,`lootyfied`) ? await token.getFlag(`world`,`lootyfied`) : false;
        if (invalid)
            continue;
	    // Remove natural weapons, natural armor, class features, spells, and feats.
            let newItems = token.actor.data.items
              .filter((item) => {
                if (item.type == 'weapon') {
                  return item.data.weaponType != 'natural';
                }
                if (item.type == 'equipment') {
                  if (!item.data.armor) return true;
                  return item.data.armor.type != 'natural';
                }
                return !['class', 'spell', 'feat'].includes(item.type);
              })
              .filter((item) => {
                // Determine if item is damaged
                const chanceOfDamagedItems = .25
                );
                const removeDamagedItems = .25
                );
                const damagedItemsMultiplier =.25
                );

                if (
                  (item.data.rarity === 'Common' ||
                  item.data.rarity === 'None') &&
                  Math.random() < chanceOfDamagedItems
                ) {
                  if (removeDamagedItems) return false;

                  item.name += ' (Damaged)';
                  item.data.price *= damagedItemsMultiplier;
                }

                return true;
              })
              .map((item) => {
                item.data.equipped = false;
                return item;
              });

            await token.actor.update({ items: [] });
            await token.actor.update({ items: newItems });


        // Change sheet to lootable, and give players permissions.
        
            let newActorData = {
              flags: {
                core: {
                  sheetClass: 'dnd5e.LootSheet5eNPC',
                },
                lootsheetnpc5e: {
                  lootsheettype: 'Loot',
                },
              },
            };

            // Handles if they already have currency set somehow
            if (typeof token.actor.data.data.currency.cp === 'number') {
              let oldCurrencyData = token.actor.data.data.currency;
              newActorData['data.currency'] = {
                cp: { value: oldCurrencyData.cp },
                ep: { value: oldCurrencyData.ep },
                gp: { value: oldCurrencyData.gp },
                pp: { value: oldCurrencyData.pp },
                sp: { value: oldCurrencyData.sp },
              };
            }
            await token.actor.update(newActorData);

            if (game.modules.get('combat-utility-belt')?.active) {
              await game.cub.removeAllConditions(token);
            }

            let lootingUsers = game.users.entries.filter((user) => {
              return (
                user.role == USER_ROLES.PLAYER ||
                user.role == USER_ROLES.TRUSTED
              );
            });
            let permissions = {};
            Object.assign(permissions, token.actor.data.permission);
            lootingUsers.forEach((user) => {
              permissions[user.data._id] = ENTITY_PERMISSIONS.OBSERVER;
            });

            await token.update({
              //overlayEffect: 'icons/svg/chest.svg',
              // effects: ['icons/containers/bags/pouch-simple-brown.webp'],
              actorData: {
                actor: {
                  flags: {
                    loot: {
                      playersPermission: ENTITY_PERMISSIONS.OBSERVER,
                    },
                  },
                },
                permission: permissions,
              },
            });
        await token.actor.update(newActorData);
        await token.setFlag(`world`,`lootyfied`,true);
    }
})();`

**Comment by SR5060** [comment]
sorry, new to this, not sure why the code didn't format appropriately

**Comment by DFreds** [comment]
No problem, I get the gist. I could definitely include a macro that does this if is it would make it easier on you. It will still require a manual trigger of the macro, though. The initial goal of this issue was to have that happen automatically. I'll include the manual version soon and look into a more automated version

**Comment by SR5060** [comment]
thanks! the nice thing is that CUB can still be used to trigger the macro automatically. so CUB triggers the macro when an NPC drops to zero and then the code addition above locates the right token to transform (unless I'm missing something, that's at least how it worked for me in 7.9)

**Comment by CaosFR** [comment]
For information, you can find a working marco here : 

https://github.com/unsoluble/fvtt-macros/tree/master/loot-swapping

This CCJMK macro look break (11 mounth last update).

**Comment by CaosFR** [comment]
For information you can use easely this module with CUB.

Go to compendium : 
- DFreds Pocket Change Macros
- Drag and drop "Convert Selected Toekns to Loot" to macro
- Raname it to "Loot" 

Go to "Condition Lab"
- Create a "Dead" condition
- Add "triggler" when NPC is dead
- Click on "Active Effect Config"
- Go to "Effect" tab and add "macro.execute" "custom" "Loo".

It's work :)

**Comment by DFreds** [comment]
@CaosFR has a good answer

**Comment by CaosFR** [comment]
@DFreds Thanks.
They are juste a little limitation. When a token are 0 hp your macro is execute automatically. 
But your macro need a selected token. If they are no selected or wrong selected token it's a problem.

As you can see on the picture, I have a other macro (macro.tokenMagic.Mort) who dont have this problem. I dont know how tokenMagic auto-select the token. Maybe it's possible to select the target (of the Triggler or the attack).

I have "code" that, maybe it's will help but can be improve : 

var verification_selection = function(){
    if(canvas.tokens.controlled.length === 1 && actor.data.data.attributes.hp.value === 0){
        const macroSupport = new game.dfreds.MacroSupport();
        macroSupport.convertSelectedTokensToLoot();
    }
    else {
        ui.notifications.error("Selectionner un token mort (5s)");
        setTimeout(check, 5000); // verifier dans 5s
    }
}
verification_selection();

I have "code" this :
